/**
 * Generates the globe's dot grid from real world geography.
 *
 * Runs at build time, never in the browser. dotted-map ships 729KB plus proj4
 * and turf, which is exactly the weight this component exists to avoid — but
 * it has the one thing a hand-written mask cannot give us, which is real
 * coastlines. So it is used here, once, and what ships is the answer.
 *
 * It only makes flat Mercator maps, so its grid is converted back to latitude
 * and longitude and re-projected onto a sphere. Verified against eight known
 * land and ocean points before it was trusted.
 *
 *   npm run globe
 */
import DottedMapImport from "dotted-map";
import { writeFileSync } from "node:fs";

const DottedMap = DottedMapImport.default ?? DottedMapImport;

// ---- camera -------------------------------------------------------------
const W = 760;
const H = 430;
const CX = 380;
const CY = 470;
const R = 365;
const LON0 = -75;
const TILT = (4 * Math.PI) / 180;
/** Degrees between dots at the equator. Roughly triples the count from 1.9. */
const SPACING = 1.35;
/**
 * How far either side of centre the globe drifts, in degrees.
 *
 * Also the culling range: a dot that never rotates into view over this sweep
 * is payload for nothing, and the far side of the planet is most of the
 * sphere.
 */
const SWEEP = 22;

const EARTH = 6378137;
const rad = (d) => (d * Math.PI) / 180;

// ---- land, from dotted-map ----------------------------------------------
// A tall grid so the coastline is sampled finely enough to resample from.
const map = new DottedMap({ height: 200, grid: "vertical" });
const raw = map.getPoints();
const gridYMax = Math.max(...raw.map((p) => p.y));

const land = raw.map(({ x, y }) => {
  const X = map.X_MIN + (x / (map.width - 1)) * map.X_RANGE;
  const Y = map.Y_MAX - (y / gridYMax) * map.Y_RANGE;
  return {
    lon: ((X / EARTH) * 180) / Math.PI,
    lat: ((2 * Math.atan(Math.exp(Y / EARTH)) - Math.PI / 2) * 180) / Math.PI,
  };
});

/**
 * A lookup keyed to whole degrees. Resampling the source grid onto our own
 * even-spaced sphere grid means asking "is there land near here", and a
 * bucketed index answers that without scanning 15,000 points per query.
 */
const buckets = new Map();
for (const p of land) {
  const k = `${Math.round(p.lat)}|${Math.round(p.lon)}`;
  if (!buckets.has(k)) buckets.set(k, []);
  buckets.get(k).push(p);
}
const NEAR = 1.15;
function isLand(lat, lon) {
  const la = Math.round(lat);
  const lo = Math.round(lon);
  for (let i = -1; i <= 1; i++) {
    for (let j = -1; j <= 1; j++) {
      for (const p of buckets.get(`${la + i}|${lo + j}`) ?? []) {
        // Longitude degrees shrink towards the poles; compare on the ground.
        const dx = (p.lon - lon) * Math.cos(rad(lat));
        if (Math.hypot(dx, p.lat - lat) < NEAR) return true;
      }
    }
  }
  return false;
}

// ---- project onto the sphere --------------------------------------------
function project(lat, lon) {
  const la = rad(lat);
  const lo = rad(lon - LON0);
  const x = Math.cos(la) * Math.sin(lo);
  const y = Math.sin(la);
  const z = Math.cos(la) * Math.cos(lo);
  const y2 = y * Math.cos(TILT) - z * Math.sin(TILT);
  const z2 = y * Math.sin(TILT) + z * Math.cos(TILT);
  return { sx: CX + R * x, sy: CY - R * y2, depth: z2 };
}

/**
 * Unit vectors on the sphere, not screen positions.
 *
 * The spin re-projects every dot each frame, so what it needs is the point in
 * three dimensions; turning that into x and y is three multiplies. Storing
 * latitude and longitude instead would mean a sine and a cosine per dot per
 * frame, which at this count is the difference between free and not.
 *
 * Only land that can ever face us is kept — the far side of the globe never
 * rotates into view within the range the spin covers, so carrying it would be
 * payload for nothing.
 */
const dots = [];
for (let lat = -82; lat <= 84; lat += SPACING) {
  const lonStep = SPACING / Math.max(Math.cos(rad(lat)), 0.2);
  for (let lon = -180; lon < 180; lon += lonStep) {
    if (!isLand(lat, lon)) continue;
    const la = rad(lat);
    const lo = rad(lon - LON0);
    const x = Math.cos(la) * Math.sin(lo);
    const y = Math.sin(la);
    const z = Math.cos(la) * Math.cos(lo);
    // Tilt is baked in: it never changes, so the client should not pay for it.
    const y2 = y * Math.cos(TILT) - z * Math.sin(TILT);
    const z2 = y * Math.sin(TILT) + z * Math.cos(TILT);
    // Visible at any point in the sweep?
    let seen = false;
    for (let a = -SWEEP; a <= SWEEP && !seen; a += 5.5) {
      const t = rad(a);
      if (-x * Math.sin(t) + z2 * Math.cos(t) > 0.04) seen = true;
    }
    if (!seen) continue;
    const r3 = (v) => Math.round(v * 1000) / 1000;
    dots.push([r3(x), r3(y2), r3(z2)]);
  }
}

const out = `// Generated by scripts/generate-globe.mjs — do not edit by hand.
// Real coastlines, sampled from dotted-map's world geometry at build time.
// Re-run \`npm run globe\` after changing the camera constants in that script.
//
// Unit vectors on the sphere, [x, y, z], with the camera tilt already applied.
// Spinning is a rotation about y, which is two multiplies and an add per dot.
export type GlobeDot = [number, number, number];

export const GLOBE = { W: ${W}, H: ${H}, CX: ${CX}, CY: ${CY}, R: ${R}, SWEEP: ${SWEEP} };

export const DOTS: GlobeDot[] = ${JSON.stringify(dots)};
`;
writeFileSync("src/content/globe-dots.ts", out);
console.log(`${dots.length} dots from ${land.length} land samples → src/content/globe-dots.ts`);
